# Generated by Django 5.0.3 on 2024-03-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default='img/avatar.jpg', null=True, upload_to='task'),
        ),
    ]
